//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Kiralama_Otomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Araclar()
        {
            this.Degerlendirme = new HashSet<Degerlendirme>();
            this.KiralamaDurumu = new HashSet<KiralamaDurumu>();
            this.Rezervasyonlar = new HashSet<Rezervasyonlar>();
        }
    
        public int arac_no { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
      
        public int yil { get; set; }
        public string yakit_tipi { get; set; }
        public string vites_tipi { get; set; }
        public Nullable<int> kilometre { get; set; }
        public int kategori_id { get; set; }
        public Nullable<int> sube_id { get; set; }
        public string resim { get; set; }
    
        public virtual AracKategorileri AracKategorileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Degerlendirme> Degerlendirme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiralamaDurumu> KiralamaDurumu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyonlar> Rezervasyonlar { get; set; }
        public virtual Subeler Subeler { get; set; }
    }
}
