//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Kiralama_Otomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degerlendirme
    {
        public int degerlendirme_no { get; set; }
        public int musteri_id { get; set; }
        public int arac_id { get; set; }
        public int puan { get; set; }
        public string yorum { get; set; }
        public System.DateTime inceleme_tarihi { get; set; }
    
        public virtual Araclar Araclar { get; set; }
        public virtual Musteriler Musteriler { get; set; }
    }
}
