//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Kiralama_Otomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EkSuruculer
    {
        public int ek_surucu_no { get; set; }
        public int rezervasyon_id { get; set; }
        public string ad { get; set; }
        public string ehliyet_bilgileri { get; set; }
    
        public virtual Rezervasyonlar Rezervasyonlar { get; set; }
    }
}
