//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Kiralama_Otomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiralamaUcretleri
    {
        public int kiralama_no { get; set; }
        public int rezervasyon_id { get; set; }
        public decimal gunluk_ucret { get; set; }
        public Nullable<decimal> ek_ucretler { get; set; }
        public decimal toplam_odeme { get; set; }
    
        public virtual Rezervasyonlar Rezervasyonlar { get; set; }
    }
}
