//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Kiralama_Otomasyonu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Arac_Kiralama_ProjesiEntities : DbContext
    {
        public Arac_Kiralama_ProjesiEntities()
            : base("name=Arac_Kiralama_ProjesiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AracKategorileri> AracKategorileri { get; set; }
        public virtual DbSet<Araclar> Araclar { get; set; }
        public virtual DbSet<Degerlendirme> Degerlendirme { get; set; }
        public virtual DbSet<EkSuruculer> EkSuruculer { get; set; }
        public virtual DbSet<KiralamaDurumu> KiralamaDurumu { get; set; }
        public virtual DbSet<KiralamaUcretleri> KiralamaUcretleri { get; set; }
        public virtual DbSet<KullaniciRolleri> KullaniciRolleri { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Odemeler> Odemeler { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Rezervasyonlar> Rezervasyonlar { get; set; }
        public virtual DbSet<Subeler> Subeler { get; set; }
        public virtual DbSet<Yonetici> Yonetici { get; set; }
    }
}
