//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Kiralama_Otomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int personel_no { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string email { get; set; }
        public string sifre { get; set; }
        public string telefon { get; set; }
        public int rol_id { get; set; }
        public Nullable<int> sube_id { get; set; }
    
        public virtual KullaniciRolleri KullaniciRolleri { get; set; }
        public virtual Subeler Subeler { get; set; }
    }
}
